/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/app'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as JoinTokenRouteImport } from './routes/join/$token'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as AppShoppingRouteImport } from './routes/app/shopping'
import { Route as AppSettingsRouteImport } from './routes/app/settings'
import { Route as AppPlanRouteImport } from './routes/app/plan'
import { Route as AppOnboardingRouteImport } from './routes/app/onboarding'
import { Route as AppLibraryIndexRouteImport } from './routes/app/library/index'
import { Route as AppProfileUsernameRouteImport } from './routes/app/profile/$username'
import { Route as AppLibraryCreateRouteImport } from './routes/app/library/create'
import { Route as AppLibraryRecipeIdRouteImport } from './routes/app/library/$recipeId'
import { Route as AppLibraryRecipeIdEditRouteImport } from './routes/app/library/$recipeId_.edit'

const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const JoinTokenRoute = JoinTokenRouteImport.update({
  id: '/join/$token',
  path: '/join/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AppShoppingRoute = AppShoppingRouteImport.update({
  id: '/shopping',
  path: '/shopping',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppPlanRoute = AppPlanRouteImport.update({
  id: '/plan',
  path: '/plan',
  getParentRoute: () => AppRoute,
} as any)
const AppOnboardingRoute = AppOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AppRoute,
} as any)
const AppLibraryIndexRoute = AppLibraryIndexRouteImport.update({
  id: '/library/',
  path: '/library/',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileUsernameRoute = AppProfileUsernameRouteImport.update({
  id: '/profile/$username',
  path: '/profile/$username',
  getParentRoute: () => AppRoute,
} as any)
const AppLibraryCreateRoute = AppLibraryCreateRouteImport.update({
  id: '/library/create',
  path: '/library/create',
  getParentRoute: () => AppRoute,
} as any)
const AppLibraryRecipeIdRoute = AppLibraryRecipeIdRouteImport.update({
  id: '/library/$recipeId',
  path: '/library/$recipeId',
  getParentRoute: () => AppRoute,
} as any)
const AppLibraryRecipeIdEditRoute = AppLibraryRecipeIdEditRouteImport.update({
  id: '/library/$recipeId_/edit',
  path: '/library/$recipeId/edit',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/app': typeof AppRouteWithChildren
  '/app/onboarding': typeof AppOnboardingRoute
  '/app/plan': typeof AppPlanRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/shopping': typeof AppShoppingRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/join/$token': typeof JoinTokenRoute
  '/app/': typeof AppIndexRoute
  '/app/library/$recipeId': typeof AppLibraryRecipeIdRoute
  '/app/library/create': typeof AppLibraryCreateRoute
  '/app/profile/$username': typeof AppProfileUsernameRoute
  '/app/library/': typeof AppLibraryIndexRoute
  '/app/library/$recipeId/edit': typeof AppLibraryRecipeIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/app/onboarding': typeof AppOnboardingRoute
  '/app/plan': typeof AppPlanRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/shopping': typeof AppShoppingRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/join/$token': typeof JoinTokenRoute
  '/app': typeof AppIndexRoute
  '/app/library/$recipeId': typeof AppLibraryRecipeIdRoute
  '/app/library/create': typeof AppLibraryCreateRoute
  '/app/profile/$username': typeof AppProfileUsernameRoute
  '/app/library': typeof AppLibraryIndexRoute
  '/app/library/$recipeId/edit': typeof AppLibraryRecipeIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/app': typeof AppRouteWithChildren
  '/app/onboarding': typeof AppOnboardingRoute
  '/app/plan': typeof AppPlanRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/shopping': typeof AppShoppingRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/join/$token': typeof JoinTokenRoute
  '/app/': typeof AppIndexRoute
  '/app/library/$recipeId': typeof AppLibraryRecipeIdRoute
  '/app/library/create': typeof AppLibraryCreateRoute
  '/app/profile/$username': typeof AppProfileUsernameRoute
  '/app/library/': typeof AppLibraryIndexRoute
  '/app/library/$recipeId_/edit': typeof AppLibraryRecipeIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/app'
    | '/app/onboarding'
    | '/app/plan'
    | '/app/settings'
    | '/app/shopping'
    | '/auth/callback'
    | '/join/$token'
    | '/app/'
    | '/app/library/$recipeId'
    | '/app/library/create'
    | '/app/profile/$username'
    | '/app/library/'
    | '/app/library/$recipeId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/app/onboarding'
    | '/app/plan'
    | '/app/settings'
    | '/app/shopping'
    | '/auth/callback'
    | '/join/$token'
    | '/app'
    | '/app/library/$recipeId'
    | '/app/library/create'
    | '/app/profile/$username'
    | '/app/library'
    | '/app/library/$recipeId/edit'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/app'
    | '/app/onboarding'
    | '/app/plan'
    | '/app/settings'
    | '/app/shopping'
    | '/auth/callback'
    | '/join/$token'
    | '/app/'
    | '/app/library/$recipeId'
    | '/app/library/create'
    | '/app/profile/$username'
    | '/app/library/'
    | '/app/library/$recipeId_/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AppRoute: typeof AppRouteWithChildren
  AuthCallbackRoute: typeof AuthCallbackRoute
  JoinTokenRoute: typeof JoinTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/join/$token': {
      id: '/join/$token'
      path: '/join/$token'
      fullPath: '/join/$token'
      preLoaderRoute: typeof JoinTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/shopping': {
      id: '/app/shopping'
      path: '/shopping'
      fullPath: '/app/shopping'
      preLoaderRoute: typeof AppShoppingRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/plan': {
      id: '/app/plan'
      path: '/plan'
      fullPath: '/app/plan'
      preLoaderRoute: typeof AppPlanRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/onboarding': {
      id: '/app/onboarding'
      path: '/onboarding'
      fullPath: '/app/onboarding'
      preLoaderRoute: typeof AppOnboardingRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/library/': {
      id: '/app/library/'
      path: '/library'
      fullPath: '/app/library/'
      preLoaderRoute: typeof AppLibraryIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/profile/$username': {
      id: '/app/profile/$username'
      path: '/profile/$username'
      fullPath: '/app/profile/$username'
      preLoaderRoute: typeof AppProfileUsernameRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/library/create': {
      id: '/app/library/create'
      path: '/library/create'
      fullPath: '/app/library/create'
      preLoaderRoute: typeof AppLibraryCreateRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/library/$recipeId': {
      id: '/app/library/$recipeId'
      path: '/library/$recipeId'
      fullPath: '/app/library/$recipeId'
      preLoaderRoute: typeof AppLibraryRecipeIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/library/$recipeId_/edit': {
      id: '/app/library/$recipeId_/edit'
      path: '/library/$recipeId/edit'
      fullPath: '/app/library/$recipeId/edit'
      preLoaderRoute: typeof AppLibraryRecipeIdEditRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppOnboardingRoute: typeof AppOnboardingRoute
  AppPlanRoute: typeof AppPlanRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppShoppingRoute: typeof AppShoppingRoute
  AppIndexRoute: typeof AppIndexRoute
  AppLibraryRecipeIdRoute: typeof AppLibraryRecipeIdRoute
  AppLibraryCreateRoute: typeof AppLibraryCreateRoute
  AppProfileUsernameRoute: typeof AppProfileUsernameRoute
  AppLibraryIndexRoute: typeof AppLibraryIndexRoute
  AppLibraryRecipeIdEditRoute: typeof AppLibraryRecipeIdEditRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppOnboardingRoute: AppOnboardingRoute,
  AppPlanRoute: AppPlanRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppShoppingRoute: AppShoppingRoute,
  AppIndexRoute: AppIndexRoute,
  AppLibraryRecipeIdRoute: AppLibraryRecipeIdRoute,
  AppLibraryCreateRoute: AppLibraryCreateRoute,
  AppProfileUsernameRoute: AppProfileUsernameRoute,
  AppLibraryIndexRoute: AppLibraryIndexRoute,
  AppLibraryRecipeIdEditRoute: AppLibraryRecipeIdEditRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AppRoute: AppRouteWithChildren,
  AuthCallbackRoute: AuthCallbackRoute,
  JoinTokenRoute: JoinTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
